name: 'CCT-i '
favicon: null
layout_spectrum: 0.5744283127132803
typography_spectrum: 0.9984720770735294
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.37130982987582684
  lightness: 0.9466384074185044
  saturation: 0.74649190553464
  rhythmicContrast: 0.48376292269676924
purpose: []
