name: 'CCT-i '
favicon: null
layout_spectrum: 0.34374
typography_spectrum: 0.9984720770735294
title: 'really cool tools... seamless, transparent and totally connected'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#21221d'
    - '#6c4e2c'
    - '#cad6c8'
    - '#af7f3c'
    - '#4bba13'
  brandStrength: 0.5625
  lightness: 0.75
  saturation: 0.74649190553464
  rhythmicContrast: 0.48376292269676924
purpose: []
